[build-system]
requires = [
  "setuptools>=69",
  "setuptools-scm[toml]>=8",
  "wheel>=0.43",
]
build-backend = "setuptools.build_meta"

[project]
name = "factowl"

version = "0.2.3"
description = "Tools for fact extraction, scoring and LLM evaluation (FactOwl)"
readme = "README.md"
authors = [
  {name = "Andrey Sakhovsky and Nikita Sushko and Skoltech NLP Lab", email = "sushko@airi.net"},
]
license = {file = "LICENSE"}
requires-python = ">=3.9"

dependencies = [
  "wikipedia",
  "jieba",
  "datasets",

]

[project.urls]
Homepage = "https://github.com/s-nlp/factowl"
Documentation = "https://github.com/s-nlp/factowl#readme"
Source = "https://github.com/s-nlp/factowl"
Issues = "https://github.com/s-nlp/factowl/issues"

[tool.setuptools]                 
[tool.setuptools.packages.find]
where   = ["."]
include = ["factowl*"]

[tool.setuptools_scm]

